/**
    Name        : SpanishUtilTest
    Date        : July 17, 2019
    Author      : Shweta Fulara
    Description : This test class is used to cover SpanishUtil class
**/
@isTest
private class SpanishUtilTest {
    
    @isTest
    static void testMethod1() {
        SpanishUtil.spanishAttachVal('W9');
        SpanishUtil.spanishAttachVal('Direct Deposit Agreement');
        SpanishUtil.spanishAttachVal('Voided Check');
        SpanishUtil.spanishAttachVal('TIN Documentation (Social Security Card or IRS Notice of Assignment of TIN)');
        SpanishUtil.spanishAttachVal('Driver’s License/Photo Id');        
        SpanishUtil.spanishAttachVal('Insurance Agreement REI');
        SpanishUtil.spanishAttachVal('Insurance Agreement Premier');
        SpanishUtil.spanishAttachVal('Insurance Agreement PPMG TX');
        SpanishUtil.spanishAttachVal('Certificate of Insurance - General Liability');        
        SpanishUtil.spanishAttachVal('Certificate of Insurance or Waiver - Workers Comp');
        SpanishUtil.spanishAttachVal('Permanent Resident Card / Green Card');
        SpanishUtil.spanishAttachVal('Employment Authorization Document / Work Permit');
        SpanishUtil.spanishAttachVal('Employment Visa');
        SpanishUtil.spanishAttachVal('Hold Harmless Agreement REI');
        SpanishUtil.spanishAttachVal('Hold Harmless Agreement PPMG TX');
        SpanishUtil.spanishAttachVal('Hold Harmless Agreement Premier');
        SpanishUtil.spanishAttachVal('License');
        SpanishUtil.spanishAttachVal('Permits');
                
        SpanishUtil.spanishAttachType('Approved / Filed');
        SpanishUtil.spanishAttachType('Uploaded');
        SpanishUtil.spanishAttachType('Rejected');
        SpanishUtil.spanishAttachType('Expired');
        SpanishUtil.spanishAttachType('New Upload Required');
        
        SpanishUtil.spanishRehabTradeVal('Cages');
        SpanishUtil.spanishRehabTradeVal('Carpet');
        SpanishUtil.spanishRehabTradeVal('Cleaning');
        SpanishUtil.spanishRehabTradeVal('Concrete');
        SpanishUtil.spanishRehabTradeVal('Electrical');
        SpanishUtil.spanishRehabTradeVal('Engineer');
        SpanishUtil.spanishRehabTradeVal('Foundation');
        SpanishUtil.spanishRehabTradeVal('Garage Doors');
        SpanishUtil.spanishRehabTradeVal('Gas');
        SpanishUtil.spanishRehabTradeVal('Handyman');
        SpanishUtil.spanishRehabTradeVal('Hardwoods');
        SpanishUtil.spanishRehabTradeVal('HVAC');
        SpanishUtil.spanishRehabTradeVal('Inspector');
        SpanishUtil.spanishRehabTradeVal('Locks');
        SpanishUtil.spanishRehabTradeVal('Move Outs');        
        SpanishUtil.spanishRehabTradeVal('Painter');
        SpanishUtil.spanishRehabTradeVal('Pest Control');
        SpanishUtil.spanishRehabTradeVal('Plumbing');
        SpanishUtil.spanishRehabTradeVal('Project Manager');
        SpanishUtil.spanishRehabTradeVal('Rehab');
        SpanishUtil.spanishRehabTradeVal('Roofs');
        SpanishUtil.spanishRehabTradeVal('Trash');
        SpanishUtil.spanishRehabTradeVal('Utility/City');
        SpanishUtil.spanishRehabTradeVal('Yard Crew');
        SpanishUtil.spanishRehabTradeVal('Inspector');
             
        SpanishUtil.primaryConInfo('El contacto principal tendrá la autoridad para cambiar, modificar o crear nuevos contactos, información bancaria, dirección comercial y números de teléfono, junto con todos los documentos archivados en este registro maestro de proveedores. Considere cuidadosamente la asignación de contacto principal.');
        
    }
    
    
}